# ref: https://www.getzola.org/documentation/getting-started/configuration/

base_url = "https://netpyoung.github.io"
title = "넷평 남짓한 공간"
description = "netpyoung's blog"
# default_language = "ko"

compile_sass = true
build_search_index = true

generate_feeds = true
feed_filenames  = ["feed.xml"]

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"
render_emoji = true

[slugify]
paths = "safe"

[extra]
title = "넷평 남짓한 공간"
[extra.paths]
feed = "/feed"
home = "/"
overview = "/overview"
company_project = "/company_project"
blog = "/blog"
study = "/study"
resume = "/resume"
external = "/external"
diary = "/diary"
resources = "/resources"

[extra.author]
name = "Eunpyoung Kim"
email = "netpyoung@gmail.com"
github = "https://github.com/netpyoung"
facebook = "https://facebook.com/netpyoung"
_googleAnalyticsTagId = "G-855BJNV9VD"